// Mocks generated by Mockito from annotations
// in kohera/test/widgets/e2ee_setup_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;
import 'dart:ui' as _i5;

import 'package:kohera/data/repositories/key_backup_repository.dart' as _i2;
import 'package:matrix/encryption.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [KeyBackupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyBackupRepository extends _i1.Mock
    implements _i2.KeyBackupRepository {
  @override
  bool get chatBackupEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#chatBackupEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get chatBackupLoading =>
      (super.noSuchMethod(
            Invocation.getter(#chatBackupLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Stream<_i4.KeyVerification> get onKeyVerificationRequest =>
      (super.noSuchMethod(
            Invocation.getter(#onKeyVerificationRequest),
            returnValue: _i3.Stream<_i4.KeyVerification>.empty(),
            returnValueForMissingStub: _i3.Stream<_i4.KeyVerification>.empty(),
          )
          as _i3.Stream<_i4.KeyVerification>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> startKeyMirror() =>
      (super.noSuchMethod(
            Invocation.method(#startKeyMirror, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopKeyMirror() =>
      (super.noSuchMethod(
            Invocation.method(#stopKeyMirror, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> checkChatBackupStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkChatBackupStatus, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> disableChatBackup() =>
      (super.noSuchMethod(
            Invocation.method(#disableChatBackup, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void resetChatBackupState() => super.noSuchMethod(
    Invocation.method(#resetChatBackupState, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> tryAutoUnlockBackup() =>
      (super.noSuchMethod(
            Invocation.method(#tryAutoUnlockBackup, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> runKeyRecovery({_i4.OpenSSSS? ssssKey}) =>
      (super.noSuchMethod(
            Invocation.method(#runKeyRecovery, [], {#ssssKey: ssssKey}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> requestMissingRoomKeys({bool? force = false}) =>
      (super.noSuchMethod(
            Invocation.method(#requestMissingRoomKeys, [], {#force: force}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getStoredRecoveryKey() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredRecoveryKey, []),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> storeRecoveryKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#storeRecoveryKey, [key]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteStoredRecoveryKey() =>
      (super.noSuchMethod(
            Invocation.method(#deleteStoredRecoveryKey, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void clearCachedPassword() => super.noSuchMethod(
    Invocation.method(#clearCachedPassword, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> updateUserDeviceKeys() =>
      (super.noSuchMethod(
            Invocation.method(#updateUserDeviceKeys, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markSessionsForBackupUpload() =>
      (super.noSuchMethod(
            Invocation.method(#markSessionsForBackupUpload, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> prepareForBootstrap({
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#prepareForBootstrap, [], {#timeout: timeout}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> hasServerKeyBackup() =>
      (super.noSuchMethod(
            Invocation.method(#hasServerKeyBackup, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.KeyVerification?> startSelfVerification() =>
      (super.noSuchMethod(
            Invocation.method(#startSelfVerification, []),
            returnValue: _i3.Future<_i4.KeyVerification?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.KeyVerification?>.value(),
          )
          as _i3.Future<_i4.KeyVerification?>);

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}
