// Mocks generated by Mockito 5.4.6 from annotations
// in kohera/test/widgets/homeserver_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:kohera/core/models/server_auth_capabilities.dart' as _i2;
import 'package:kohera/core/services/sub_services/auth_service.dart' as _i3;
import 'package:matrix/matrix.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeServerAuthCapabilities_0 extends _i1.SmartFake
    implements _i2.ServerAuthCapabilities {
  _FakeServerAuthCapabilities_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set isLoggedIn(bool? value) => super.noSuchMethod(
    Invocation.setter(#isLoggedIn, value),
    returnValueForMissingStub: null,
  );

  @override
  set loginError(String? value) => super.noSuchMethod(
    Invocation.setter(#loginError, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<bool> login({
    required String? homeserver,
    required String? username,
    required String? password,
    bool? rememberCredentials = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #homeserver: homeserver,
              #username: username,
              #password: password,
              #rememberCredentials: rememberCredentials,
            }),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> completeSsoLogin({
    required String? homeserver,
    required String? loginToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeSsoLogin, [], {
              #homeserver: homeserver,
              #loginToken: loginToken,
            }),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> completeRegistration(
    _i5.RegisterResponse? response, {
    String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #completeRegistration,
              [response],
              {#password: password},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void activateRestoredSession() => super.noSuchMethod(
    Invocation.method(#activateRestoredSession, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> handleServerLogout() =>
      (super.noSuchMethod(
            Invocation.method(#handleServerLogout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveSessionBackup() =>
      (super.noSuchMethod(
            Invocation.method(#saveSessionBackup, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ServerAuthCapabilities> getServerAuthCapabilities(
    String? homeserver, {
    required bool? isLoggedIn,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getServerAuthCapabilities,
              [homeserver],
              {#isLoggedIn: isLoggedIn},
            ),
            returnValue: _i4.Future<_i2.ServerAuthCapabilities>.value(
              _FakeServerAuthCapabilities_0(
                this,
                Invocation.method(
                  #getServerAuthCapabilities,
                  [homeserver],
                  {#isLoggedIn: isLoggedIn},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.ServerAuthCapabilities>.value(
                  _FakeServerAuthCapabilities_0(
                    this,
                    Invocation.method(
                      #getServerAuthCapabilities,
                      [homeserver],
                      {#isLoggedIn: isLoggedIn},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.ServerAuthCapabilities>);

  @override
  bool isPermanentAuthFailure(Object? error) =>
      (super.noSuchMethod(
            Invocation.method(#isPermanentAuthFailure, [error]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> clearSessionKeys() =>
      (super.noSuchMethod(
            Invocation.method(#clearSessionKeys, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveLoginCredentials({
    required String? homeserver,
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveLoginCredentials, [], {
              #homeserver: homeserver,
              #username: username,
              #password: password,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<({String password, String username})?> loadLoginCredentials(
    String? homeserver,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadLoginCredentials, [homeserver]),
            returnValue:
                _i4.Future<({String password, String username})?>.value(),
            returnValueForMissingStub:
                _i4.Future<({String password, String username})?>.value(),
          )
          as _i4.Future<({String password, String username})?>);

  @override
  _i4.Future<void> clearLoginCredentials(String? homeserver) =>
      (super.noSuchMethod(
            Invocation.method(#clearLoginCredentials, [homeserver]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> migrateStorageKeys() =>
      (super.noSuchMethod(
            Invocation.method(#migrateStorageKeys, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> persistCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#persistCredentials, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
