// Mocks generated by Mockito 5.4.6 from annotations
// in kohera/test/widgets/homeserver_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i18;
import 'dart:ui' as _i19;

import 'package:flutter/services.dart' as _i20;
import 'package:flutter/widgets.dart' as _i21;
import 'package:kohera/core/models/server_auth_capabilities.dart' as _i15;
import 'package:kohera/core/services/matrix_service.dart' as _i16;
import 'package:kohera/core/services/sticker_pack_service.dart' as _i14;
import 'package:kohera/core/services/sub_services/auth_service.dart' as _i11;
import 'package:kohera/core/services/sub_services/chat_backup_service.dart'
    as _i6;
import 'package:kohera/core/services/sub_services/outbox_service.dart' as _i12;
import 'package:kohera/core/services/sub_services/presence_service.dart' as _i8;
import 'package:kohera/core/services/sub_services/selection_service.dart'
    as _i7;
import 'package:kohera/core/services/sub_services/space_access_service.dart'
    as _i9;
import 'package:kohera/core/services/sub_services/sync_service.dart' as _i10;
import 'package:kohera/core/services/sub_services/uia_service.dart' as _i5;
import 'package:kohera/features/notifications/services/call_push_rule_manager.dart'
    as _i2;
import 'package:kohera/features/notifications/services/megolm_key_mirror.dart'
    as _i3;
import 'package:kohera/shared/services/avatar_resolver.dart' as _i13;
import 'package:matrix/matrix.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCallPushRuleManager_0 extends _i1.SmartFake
    implements _i2.CallPushRuleManager {
  _FakeCallPushRuleManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMegolmKeyMirror_1 extends _i1.SmartFake
    implements _i3.MegolmKeyMirror {
  _FakeMegolmKeyMirror_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_2 extends _i1.SmartFake implements _i4.Client {
  _FakeClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUiaService_3 extends _i1.SmartFake implements _i5.UiaService {
  _FakeUiaService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChatBackupService_4 extends _i1.SmartFake
    implements _i6.ChatBackupService {
  _FakeChatBackupService_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectionService_5 extends _i1.SmartFake
    implements _i7.SelectionService {
  _FakeSelectionService_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePresenceService_6 extends _i1.SmartFake
    implements _i8.PresenceService {
  _FakePresenceService_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpaceAccessService_7 extends _i1.SmartFake
    implements _i9.SpaceAccessService {
  _FakeSpaceAccessService_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncService_8 extends _i1.SmartFake implements _i10.SyncService {
  _FakeSyncService_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthService_9 extends _i1.SmartFake implements _i11.AuthService {
  _FakeAuthService_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOutboxService_10 extends _i1.SmartFake
    implements _i12.OutboxService {
  _FakeOutboxService_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAvatarResolver_11 extends _i1.SmartFake
    implements _i13.AvatarResolver {
  _FakeAvatarResolver_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStickerPackService_12 extends _i1.SmartFake
    implements _i14.StickerPackService {
  _FakeStickerPackService_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeServerAuthCapabilities_13 extends _i1.SmartFake
    implements _i15.ServerAuthCapabilities {
  _FakeServerAuthCapabilities_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MatrixService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatrixService extends _i1.Mock implements _i16.MatrixService {
  @override
  _i2.CallPushRuleManager get callPushRuleManager => (super.noSuchMethod(
        Invocation.getter(#callPushRuleManager),
        returnValue: _FakeCallPushRuleManager_0(
          this,
          Invocation.getter(#callPushRuleManager),
        ),
        returnValueForMissingStub: _FakeCallPushRuleManager_0(
          this,
          Invocation.getter(#callPushRuleManager),
        ),
      ) as _i2.CallPushRuleManager);

  @override
  _i3.MegolmKeyMirror get keyMirror => (super.noSuchMethod(
        Invocation.getter(#keyMirror),
        returnValue: _FakeMegolmKeyMirror_1(
          this,
          Invocation.getter(#keyMirror),
        ),
        returnValueForMissingStub: _FakeMegolmKeyMirror_1(
          this,
          Invocation.getter(#keyMirror),
        ),
      ) as _i3.MegolmKeyMirror);

  @override
  String get clientName => (super.noSuchMethod(
        Invocation.getter(#clientName),
        returnValue: _i17.dummyValue<String>(
          this,
          Invocation.getter(#clientName),
        ),
        returnValueForMissingStub: _i17.dummyValue<String>(
          this,
          Invocation.getter(#clientName),
        ),
      ) as String);

  @override
  _i4.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_2(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeClient_2(
          this,
          Invocation.getter(#client),
        ),
      ) as _i4.Client);

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get disposed => (super.noSuchMethod(
        Invocation.getter(#disposed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.UiaService get uia => (super.noSuchMethod(
        Invocation.getter(#uia),
        returnValue: _FakeUiaService_3(
          this,
          Invocation.getter(#uia),
        ),
        returnValueForMissingStub: _FakeUiaService_3(
          this,
          Invocation.getter(#uia),
        ),
      ) as _i5.UiaService);

  @override
  _i6.ChatBackupService get chatBackup => (super.noSuchMethod(
        Invocation.getter(#chatBackup),
        returnValue: _FakeChatBackupService_4(
          this,
          Invocation.getter(#chatBackup),
        ),
        returnValueForMissingStub: _FakeChatBackupService_4(
          this,
          Invocation.getter(#chatBackup),
        ),
      ) as _i6.ChatBackupService);

  @override
  _i7.SelectionService get selection => (super.noSuchMethod(
        Invocation.getter(#selection),
        returnValue: _FakeSelectionService_5(
          this,
          Invocation.getter(#selection),
        ),
        returnValueForMissingStub: _FakeSelectionService_5(
          this,
          Invocation.getter(#selection),
        ),
      ) as _i7.SelectionService);

  @override
  _i8.PresenceService get presence => (super.noSuchMethod(
        Invocation.getter(#presence),
        returnValue: _FakePresenceService_6(
          this,
          Invocation.getter(#presence),
        ),
        returnValueForMissingStub: _FakePresenceService_6(
          this,
          Invocation.getter(#presence),
        ),
      ) as _i8.PresenceService);

  @override
  _i9.SpaceAccessService get spaceAccess => (super.noSuchMethod(
        Invocation.getter(#spaceAccess),
        returnValue: _FakeSpaceAccessService_7(
          this,
          Invocation.getter(#spaceAccess),
        ),
        returnValueForMissingStub: _FakeSpaceAccessService_7(
          this,
          Invocation.getter(#spaceAccess),
        ),
      ) as _i9.SpaceAccessService);

  @override
  _i10.SyncService get sync => (super.noSuchMethod(
        Invocation.getter(#sync),
        returnValue: _FakeSyncService_8(
          this,
          Invocation.getter(#sync),
        ),
        returnValueForMissingStub: _FakeSyncService_8(
          this,
          Invocation.getter(#sync),
        ),
      ) as _i10.SyncService);

  @override
  _i11.AuthService get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeAuthService_9(
          this,
          Invocation.getter(#auth),
        ),
        returnValueForMissingStub: _FakeAuthService_9(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i11.AuthService);

  @override
  _i12.OutboxService get outbox => (super.noSuchMethod(
        Invocation.getter(#outbox),
        returnValue: _FakeOutboxService_10(
          this,
          Invocation.getter(#outbox),
        ),
        returnValueForMissingStub: _FakeOutboxService_10(
          this,
          Invocation.getter(#outbox),
        ),
      ) as _i12.OutboxService);

  @override
  _i13.AvatarResolver get avatarResolver => (super.noSuchMethod(
        Invocation.getter(#avatarResolver),
        returnValue: _FakeAvatarResolver_11(
          this,
          Invocation.getter(#avatarResolver),
        ),
        returnValueForMissingStub: _FakeAvatarResolver_11(
          this,
          Invocation.getter(#avatarResolver),
        ),
      ) as _i13.AvatarResolver);

  @override
  _i14.StickerPackService get stickerPacks => (super.noSuchMethod(
        Invocation.getter(#stickerPacks),
        returnValue: _FakeStickerPackService_12(
          this,
          Invocation.getter(#stickerPacks),
        ),
        returnValueForMissingStub: _FakeStickerPackService_12(
          this,
          Invocation.getter(#stickerPacks),
        ),
      ) as _i14.StickerPackService);

  @override
  bool get hasSkippedSetup => (super.noSuchMethod(
        Invocation.getter(#hasSkippedSetup),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set callPushRuleManager(_i2.CallPushRuleManager? value) => super.noSuchMethod(
        Invocation.setter(
          #callPushRuleManager,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set keyMirror(_i3.MegolmKeyMirror? value) => super.noSuchMethod(
        Invocation.setter(
          #keyMirror,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoggedInForTest(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoggedInForTest,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set uia(_i5.UiaService? value) => super.noSuchMethod(
        Invocation.setter(
          #uia,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set chatBackup(_i6.ChatBackupService? value) => super.noSuchMethod(
        Invocation.setter(
          #chatBackup,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set selection(_i7.SelectionService? value) => super.noSuchMethod(
        Invocation.setter(
          #selection,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set presence(_i8.PresenceService? value) => super.noSuchMethod(
        Invocation.setter(
          #presence,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set spaceAccess(_i9.SpaceAccessService? value) => super.noSuchMethod(
        Invocation.setter(
          #spaceAccess,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set sync(_i10.SyncService? value) => super.noSuchMethod(
        Invocation.setter(
          #sync,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set auth(_i11.AuthService? value) => super.noSuchMethod(
        Invocation.setter(
          #auth,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set outbox(_i12.OutboxService? value) => super.noSuchMethod(
        Invocation.setter(
          #outbox,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set avatarResolver(_i13.AvatarResolver? value) => super.noSuchMethod(
        Invocation.setter(
          #avatarResolver,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set stickerPacks(_i14.StickerPackService? value) => super.noSuchMethod(
        Invocation.setter(
          #stickerPacks,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i18.Future<void> activateSessionForTest() => (super.noSuchMethod(
        Invocation.method(
          #activateSessionForTest,
          [],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void skipSetup() => super.noSuchMethod(
        Invocation.method(
          #skipSetup,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeAppLifecycleState(_i19.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeAppLifecycleState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<void> init({bool? restoreSession = true}) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#restoreSession: restoreSession},
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<bool> login({
    required String? homeserver,
    required String? username,
    required String? password,
    bool? rememberCredentials = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #homeserver: homeserver,
            #username: username,
            #password: password,
            #rememberCredentials: rememberCredentials,
          },
        ),
        returnValue: _i18.Future<bool>.value(false),
        returnValueForMissingStub: _i18.Future<bool>.value(false),
      ) as _i18.Future<bool>);

  @override
  _i18.Future<bool> completeSsoLogin({
    required String? homeserver,
    required String? loginToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeSsoLogin,
          [],
          {
            #homeserver: homeserver,
            #loginToken: loginToken,
          },
        ),
        returnValue: _i18.Future<bool>.value(false),
        returnValueForMissingStub: _i18.Future<bool>.value(false),
      ) as _i18.Future<bool>);

  @override
  _i18.Future<void> completeRegistration(
    _i4.RegisterResponse? response, {
    String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeRegistration,
          [response],
          {#password: password},
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<void> handleSoftLogout() => (super.noSuchMethod(
        Invocation.method(
          #handleSoftLogout,
          [],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  void addListener(_i19.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i19.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<bool> didPopRoute() => (super.noSuchMethod(
        Invocation.method(
          #didPopRoute,
          [],
        ),
        returnValue: _i18.Future<bool>.value(false),
        returnValueForMissingStub: _i18.Future<bool>.value(false),
      ) as _i18.Future<bool>);

  @override
  bool handleStartBackGesture(_i20.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleStartBackGesture,
          [backEvent],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void handleUpdateBackGestureProgress(_i20.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(
          #handleUpdateBackGestureProgress,
          [backEvent],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCommitBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCancelBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleStatusBarTap() => super.noSuchMethod(
        Invocation.method(
          #handleStatusBarTap,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<bool> didPushRoute(String? route) => (super.noSuchMethod(
        Invocation.method(
          #didPushRoute,
          [route],
        ),
        returnValue: _i18.Future<bool>.value(false),
        returnValueForMissingStub: _i18.Future<bool>.value(false),
      ) as _i18.Future<bool>);

  @override
  _i18.Future<bool> didPushRouteInformation(
          _i21.RouteInformation? routeInformation) =>
      (super.noSuchMethod(
        Invocation.method(
          #didPushRouteInformation,
          [routeInformation],
        ),
        returnValue: _i18.Future<bool>.value(false),
        returnValueForMissingStub: _i18.Future<bool>.value(false),
      ) as _i18.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
        Invocation.method(
          #didChangeMetrics,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
        Invocation.method(
          #didChangeTextScaleFactor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
        Invocation.method(
          #didChangePlatformBrightness,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeLocales(List<_i19.Locale>? locales) => super.noSuchMethod(
        Invocation.method(
          #didChangeLocales,
          [locales],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeViewFocus(_i19.ViewFocusEvent? event) => super.noSuchMethod(
        Invocation.method(
          #didChangeViewFocus,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<_i19.AppExitResponse> didRequestAppExit() => (super.noSuchMethod(
        Invocation.method(
          #didRequestAppExit,
          [],
        ),
        returnValue:
            _i18.Future<_i19.AppExitResponse>.value(_i19.AppExitResponse.exit),
        returnValueForMissingStub:
            _i18.Future<_i19.AppExitResponse>.value(_i19.AppExitResponse.exit),
      ) as _i18.Future<_i19.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
        Invocation.method(
          #didHaveMemoryPressure,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
        Invocation.method(
          #didChangeAccessibilityFeatures,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i11.AuthService {
  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set isLoggedIn(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoggedIn,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set loginError(String? value) => super.noSuchMethod(
        Invocation.setter(
          #loginError,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i18.Future<bool> login({
    required String? homeserver,
    required String? username,
    required String? password,
    bool? rememberCredentials = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #homeserver: homeserver,
            #username: username,
            #password: password,
            #rememberCredentials: rememberCredentials,
          },
        ),
        returnValue: _i18.Future<bool>.value(false),
        returnValueForMissingStub: _i18.Future<bool>.value(false),
      ) as _i18.Future<bool>);

  @override
  _i18.Future<bool> completeSsoLogin({
    required String? homeserver,
    required String? loginToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeSsoLogin,
          [],
          {
            #homeserver: homeserver,
            #loginToken: loginToken,
          },
        ),
        returnValue: _i18.Future<bool>.value(false),
        returnValueForMissingStub: _i18.Future<bool>.value(false),
      ) as _i18.Future<bool>);

  @override
  _i18.Future<void> completeRegistration(
    _i4.RegisterResponse? response, {
    String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeRegistration,
          [response],
          {#password: password},
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  void activateRestoredSession() => super.noSuchMethod(
        Invocation.method(
          #activateRestoredSession,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<void> handleServerLogout() => (super.noSuchMethod(
        Invocation.method(
          #handleServerLogout,
          [],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<void> saveSessionBackup() => (super.noSuchMethod(
        Invocation.method(
          #saveSessionBackup,
          [],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<_i15.ServerAuthCapabilities> getServerAuthCapabilities(
    String? homeserver, {
    required bool? isLoggedIn,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServerAuthCapabilities,
          [homeserver],
          {#isLoggedIn: isLoggedIn},
        ),
        returnValue: _i18.Future<_i15.ServerAuthCapabilities>.value(
            _FakeServerAuthCapabilities_13(
          this,
          Invocation.method(
            #getServerAuthCapabilities,
            [homeserver],
            {#isLoggedIn: isLoggedIn},
          ),
        )),
        returnValueForMissingStub:
            _i18.Future<_i15.ServerAuthCapabilities>.value(
                _FakeServerAuthCapabilities_13(
          this,
          Invocation.method(
            #getServerAuthCapabilities,
            [homeserver],
            {#isLoggedIn: isLoggedIn},
          ),
        )),
      ) as _i18.Future<_i15.ServerAuthCapabilities>);

  @override
  bool isPermanentAuthFailure(Object? error) => (super.noSuchMethod(
        Invocation.method(
          #isPermanentAuthFailure,
          [error],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i18.Future<void> clearSessionKeys() => (super.noSuchMethod(
        Invocation.method(
          #clearSessionKeys,
          [],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<void> saveLoginCredentials({
    required String? homeserver,
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLoginCredentials,
          [],
          {
            #homeserver: homeserver,
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<({String password, String username})?> loadLoginCredentials(
          String? homeserver) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadLoginCredentials,
          [homeserver],
        ),
        returnValue: _i18.Future<({String password, String username})?>.value(),
        returnValueForMissingStub:
            _i18.Future<({String password, String username})?>.value(),
      ) as _i18.Future<({String password, String username})?>);

  @override
  _i18.Future<void> clearLoginCredentials(String? homeserver) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearLoginCredentials,
          [homeserver],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<void> migrateStorageKeys() => (super.noSuchMethod(
        Invocation.method(
          #migrateStorageKeys,
          [],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  _i18.Future<void> persistCredentials() => (super.noSuchMethod(
        Invocation.method(
          #persistCredentials,
          [],
        ),
        returnValue: _i18.Future<void>.value(),
        returnValueForMissingStub: _i18.Future<void>.value(),
      ) as _i18.Future<void>);

  @override
  void addListener(_i19.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i19.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
