// Mocks generated by Mockito 5.4.6 from annotations
// in kohera/test/services/chat_search_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kohera/features/chat/models/room_search_result.dart' as _i3;
import 'package:kohera/features/chat/services/room_search_service.dart' as _i4;
import 'package:matrix/matrix.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoomSearchResponse_1 extends _i1.SmartFake
    implements _i3.RoomSearchResponse {
  _FakeRoomSearchResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RoomSearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoomSearchService extends _i1.Mock implements _i4.RoomSearchService {
  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
            returnValueForMissingStub: _FakeClient_0(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.Client);

  @override
  _i5.Future<_i3.RoomSearchResponse> search({
    required String? roomId,
    required String? query,
    String? nextBatch,
    int? limit = 50,
    String? senderFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#search, [], {
              #roomId: roomId,
              #query: query,
              #nextBatch: nextBatch,
              #limit: limit,
              #senderFilter: senderFilter,
            }),
            returnValue: _i5.Future<_i3.RoomSearchResponse>.value(
              _FakeRoomSearchResponse_1(
                this,
                Invocation.method(#search, [], {
                  #roomId: roomId,
                  #query: query,
                  #nextBatch: nextBatch,
                  #limit: limit,
                  #senderFilter: senderFilter,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.RoomSearchResponse>.value(
              _FakeRoomSearchResponse_1(
                this,
                Invocation.method(#search, [], {
                  #roomId: roomId,
                  #query: query,
                  #nextBatch: nextBatch,
                  #limit: limit,
                  #senderFilter: senderFilter,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.RoomSearchResponse>);
}
