// Mocks generated by Mockito from annotations
// in kohera/test/widgets/chat/emoji_autocomplete_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i11;

import 'package:kohera/core/models/emoji_gg_pack.dart' as _i9;
import 'package:kohera/core/services/emoji_gg_service.dart' as _i10;
import 'package:kohera/core/services/sticker_pack_service.dart' as _i5;
import 'package:kohera/data/models/kohera_sticker_pack.dart' as _i6;
import 'package:kohera/data/models/sticker_pack.dart' as _i7;
import 'package:kohera/data/services/matrix_client_service.dart' as _i2;
import 'package:matrix/matrix.dart' as _i3;
import 'package:matrix/src/models/timeline_chunk.dart' as _i14;
import 'package:matrix/src/utils/cached_stream_controller.dart' as _i4;
import 'package:matrix/src/utils/space_child.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMatrixClientService_0 extends _i1.SmartFake
    implements _i2.MatrixClientService {
  _FakeMatrixClientService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoomSummary_1 extends _i1.SmartFake implements _i3.RoomSummary {
  _FakeRoomSummary_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCachedStreamController_2<T> extends _i1.SmartFake
    implements _i4.CachedStreamController<T> {
  _FakeCachedStreamController_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_3 extends _i1.SmartFake implements _i3.Client {
  _FakeClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_4 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLatestReceiptState_5 extends _i1.SmartFake
    implements _i3.LatestReceiptState {
  _FakeLatestReceiptState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncUpdate_6 extends _i1.SmartFake implements _i3.SyncUpdate {
  _FakeSyncUpdate_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTimeline_7 extends _i1.SmartFake implements _i3.Timeline {
  _FakeTimeline_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_8 extends _i1.SmartFake implements _i3.User {
  _FakeUser_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_9 extends _i1.SmartFake implements Uri {
  _FakeUri_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StickerPackService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStickerPackService extends _i1.Mock
    implements _i5.StickerPackService {
  @override
  _i2.MatrixClientService get matrixClientService =>
      (super.noSuchMethod(
            Invocation.getter(#matrixClientService),
            returnValue: _FakeMatrixClientService_0(
              this,
              Invocation.getter(#matrixClientService),
            ),
            returnValueForMissingStub: _FakeMatrixClientService_0(
              this,
              Invocation.getter(#matrixClientService),
            ),
          )
          as _i2.MatrixClientService);

  @override
  List<_i6.KoheraStickerPack> get koheraAccountPacks =>
      (super.noSuchMethod(
            Invocation.getter(#koheraAccountPacks),
            returnValue: <_i6.KoheraStickerPack>[],
            returnValueForMissingStub: <_i6.KoheraStickerPack>[],
          )
          as List<_i6.KoheraStickerPack>);

  @override
  List<_i7.StickerPack> get accountPacks =>
      (super.noSuchMethod(
            Invocation.getter(#accountPacks),
            returnValue: <_i7.StickerPack>[],
            returnValueForMissingStub: <_i7.StickerPack>[],
          )
          as List<_i7.StickerPack>);

  @override
  List<_i7.StickerPack> get importedPacks =>
      (super.noSuchMethod(
            Invocation.getter(#importedPacks),
            returnValue: <_i7.StickerPack>[],
            returnValueForMissingStub: <_i7.StickerPack>[],
          )
          as List<_i7.StickerPack>);

  @override
  Set<String> get importedEmojiGgSlugs =>
      (super.noSuchMethod(
            Invocation.getter(#importedEmojiGgSlugs),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i6.KoheraStickerPack> koheraAvailableRoomPacks() =>
      (super.noSuchMethod(
            Invocation.method(#koheraAvailableRoomPacks, []),
            returnValue: <_i6.KoheraStickerPack>[],
            returnValueForMissingStub: <_i6.KoheraStickerPack>[],
          )
          as List<_i6.KoheraStickerPack>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i7.StickerPack> packsForRoom(_i3.Room? room) =>
      (super.noSuchMethod(
            Invocation.method(#packsForRoom, [room]),
            returnValue: <_i7.StickerPack>[],
            returnValueForMissingStub: <_i7.StickerPack>[],
          )
          as List<_i7.StickerPack>);

  @override
  List<_i7.StickerPack> availableRoomPacks() =>
      (super.noSuchMethod(
            Invocation.method(#availableRoomPacks, []),
            returnValue: <_i7.StickerPack>[],
            returnValueForMissingStub: <_i7.StickerPack>[],
          )
          as List<_i7.StickerPack>);

  @override
  _i8.Future<void> subscribeToRoomPack(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToRoomPack, [roomId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> unsubscribeFromRoomPack(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromRoomPack, [roomId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> reorderSubscriptions(List<String>? orderedIds) =>
      (super.noSuchMethod(
            Invocation.method(#reorderSubscriptions, [orderedIds]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<_i5.ImportProgress> importEmojiGgPack(
    _i9.EmojiGgPack? pack,
    _i10.EmojiGgService? emojiGgService,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#importEmojiGgPack, [pack, emojiGgService]),
            returnValue: _i8.Stream<_i5.ImportProgress>.empty(),
            returnValueForMissingStub: _i8.Stream<_i5.ImportProgress>.empty(),
          )
          as _i8.Stream<_i5.ImportProgress>);

  @override
  _i8.Future<void> removeImportedPack(String? packId) =>
      (super.noSuchMethod(
            Invocation.method(#removeImportedPack, [packId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Room].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoom extends _i1.Mock implements _i3.Room {
  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i12.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  _i3.Membership get membership =>
      (super.noSuchMethod(
            Invocation.getter(#membership),
            returnValue: _i3.Membership.ban,
            returnValueForMissingStub: _i3.Membership.ban,
          )
          as _i3.Membership);

  @override
  int get notificationCount =>
      (super.noSuchMethod(
            Invocation.getter(#notificationCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get highlightCount =>
      (super.noSuchMethod(
            Invocation.getter(#highlightCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i3.RoomSummary get summary =>
      (super.noSuchMethod(
            Invocation.getter(#summary),
            returnValue: _FakeRoomSummary_1(this, Invocation.getter(#summary)),
            returnValueForMissingStub: _FakeRoomSummary_1(
              this,
              Invocation.getter(#summary),
            ),
          )
          as _i3.RoomSummary);

  @override
  Map<String, Map<String, _i3.StrippedStateEvent>> get states =>
      (super.noSuchMethod(
            Invocation.getter(#states),
            returnValue: <String, Map<String, _i3.StrippedStateEvent>>{},
            returnValueForMissingStub:
                <String, Map<String, _i3.StrippedStateEvent>>{},
          )
          as Map<String, Map<String, _i3.StrippedStateEvent>>);

  @override
  Map<String, _i3.BasicEvent> get ephemerals =>
      (super.noSuchMethod(
            Invocation.getter(#ephemerals),
            returnValue: <String, _i3.BasicEvent>{},
            returnValueForMissingStub: <String, _i3.BasicEvent>{},
          )
          as Map<String, _i3.BasicEvent>);

  @override
  Map<String, _i3.BasicEvent> get roomAccountData =>
      (super.noSuchMethod(
            Invocation.getter(#roomAccountData),
            returnValue: <String, _i3.BasicEvent>{},
            returnValueForMissingStub: <String, _i3.BasicEvent>{},
          )
          as Map<String, _i3.BasicEvent>);

  @override
  List<_i8.Completer<dynamic>> get sendingQueue =>
      (super.noSuchMethod(
            Invocation.getter(#sendingQueue),
            returnValue: <_i8.Completer<dynamic>>[],
            returnValueForMissingStub: <_i8.Completer<dynamic>>[],
          )
          as List<_i8.Completer<dynamic>>);

  @override
  List<String> get sendingQueueEventsByTxId =>
      (super.noSuchMethod(
            Invocation.getter(#sendingQueueEventsByTxId),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  bool get partial =>
      (super.noSuchMethod(
            Invocation.getter(#partial),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get fullyRead =>
      (super.noSuchMethod(
            Invocation.getter(#fullyRead),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#fullyRead),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#fullyRead),
            ),
          )
          as String);

  @override
  _i4.CachedStreamController<String> get onUpdate =>
      (super.noSuchMethod(
            Invocation.getter(#onUpdate),
            returnValue: _FakeCachedStreamController_2<String>(
              this,
              Invocation.getter(#onUpdate),
            ),
            returnValueForMissingStub: _FakeCachedStreamController_2<String>(
              this,
              Invocation.getter(#onUpdate),
            ),
          )
          as _i4.CachedStreamController<String>);

  @override
  _i4.CachedStreamController<String> get onSessionKeyReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onSessionKeyReceived),
            returnValue: _FakeCachedStreamController_2<String>(
              this,
              Invocation.getter(#onSessionKeyReceived),
            ),
            returnValueForMissingStub: _FakeCachedStreamController_2<String>(
              this,
              Invocation.getter(#onSessionKeyReceived),
            ),
          )
          as _i4.CachedStreamController<String>);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  List<String> get pinnedEventIds =>
      (super.noSuchMethod(
            Invocation.getter(#pinnedEventIds),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  String get topic =>
      (super.noSuchMethod(
            Invocation.getter(#topic),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#topic),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#topic),
            ),
          )
          as String);

  @override
  String get canonicalAlias =>
      (super.noSuchMethod(
            Invocation.getter(#canonicalAlias),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#canonicalAlias),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#canonicalAlias),
            ),
          )
          as String);

  @override
  bool get isDirectChat =>
      (super.noSuchMethod(
            Invocation.getter(#isDirectChat),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i3.User> get typingUsers =>
      (super.noSuchMethod(
            Invocation.getter(#typingUsers),
            returnValue: <_i3.User>[],
            returnValueForMissingStub: <_i3.User>[],
          )
          as List<_i3.User>);

  @override
  _i3.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_3(this, Invocation.getter(#client)),
            returnValueForMissingStub: _FakeClient_3(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i3.Client);

  @override
  bool get isAbandonedDMRoom =>
      (super.noSuchMethod(
            Invocation.getter(#isAbandonedDMRoom),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get displayname =>
      (super.noSuchMethod(
            Invocation.getter(#displayname),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#displayname),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#displayname),
            ),
          )
          as String);

  @override
  DateTime get latestEventReceivedTime =>
      (super.noSuchMethod(
            Invocation.getter(#latestEventReceivedTime),
            returnValue: _FakeDateTime_4(
              this,
              Invocation.getter(#latestEventReceivedTime),
            ),
            returnValueForMissingStub: _FakeDateTime_4(
              this,
              Invocation.getter(#latestEventReceivedTime),
            ),
          )
          as DateTime);

  @override
  Map<String, _i3.Tag> get tags =>
      (super.noSuchMethod(
            Invocation.getter(#tags),
            returnValue: <String, _i3.Tag>{},
            returnValueForMissingStub: <String, _i3.Tag>{},
          )
          as Map<String, _i3.Tag>);

  @override
  bool get markedUnread =>
      (super.noSuchMethod(
            Invocation.getter(#markedUnread),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasNewMessages =>
      (super.noSuchMethod(
            Invocation.getter(#hasNewMessages),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.LatestReceiptState get receiptState =>
      (super.noSuchMethod(
            Invocation.getter(#receiptState),
            returnValue: _FakeLatestReceiptState_5(
              this,
              Invocation.getter(#receiptState),
            ),
            returnValueForMissingStub: _FakeLatestReceiptState_5(
              this,
              Invocation.getter(#receiptState),
            ),
          )
          as _i3.LatestReceiptState);

  @override
  bool get isUnread =>
      (super.noSuchMethod(
            Invocation.getter(#isUnread),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isUnreadOrInvited =>
      (super.noSuchMethod(
            Invocation.getter(#isUnreadOrInvited),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<_i3.SyncUpdate> get waitForSync =>
      (super.noSuchMethod(
            Invocation.getter(#waitForSync),
            returnValue: _i8.Future<_i3.SyncUpdate>.value(
              _FakeSyncUpdate_6(this, Invocation.getter(#waitForSync)),
            ),
            returnValueForMissingStub: _i8.Future<_i3.SyncUpdate>.value(
              _FakeSyncUpdate_6(this, Invocation.getter(#waitForSync)),
            ),
          )
          as _i8.Future<_i3.SyncUpdate>);

  @override
  bool get isFavourite =>
      (super.noSuchMethod(
            Invocation.getter(#isFavourite),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLowPriority =>
      (super.noSuchMethod(
            Invocation.getter(#isLowPriority),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isFederated =>
      (super.noSuchMethod(
            Invocation.getter(#isFederated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isArchived =>
      (super.noSuchMethod(
            Invocation.getter(#isArchived),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get participantListComplete =>
      (super.noSuchMethod(
            Invocation.getter(#participantListComplete),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Set<String> get creatorUserIds =>
      (super.noSuchMethod(
            Invocation.getter(#creatorUserIds),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  _i3.PowerLevel get ownPowerLevel =>
      (super.noSuchMethod(
            Invocation.getter(#ownPowerLevel),
            returnValue: (0 as _i3.PowerLevel),
            returnValueForMissingStub: (0 as _i3.PowerLevel),
          )
          as _i3.PowerLevel);

  @override
  bool get canBan =>
      (super.noSuchMethod(
            Invocation.getter(#canBan),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get groupCallsEnabledForEveryone =>
      (super.noSuchMethod(
            Invocation.getter(#groupCallsEnabledForEveryone),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canJoinGroupCall =>
      (super.noSuchMethod(
            Invocation.getter(#canJoinGroupCall),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canSendDefaultMessages =>
      (super.noSuchMethod(
            Invocation.getter(#canSendDefaultMessages),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canInvite =>
      (super.noSuchMethod(
            Invocation.getter(#canInvite),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canKick =>
      (super.noSuchMethod(
            Invocation.getter(#canKick),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canRedact =>
      (super.noSuchMethod(
            Invocation.getter(#canRedact),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canSendDefaultStates =>
      (super.noSuchMethod(
            Invocation.getter(#canSendDefaultStates),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canChangePowerLevel =>
      (super.noSuchMethod(
            Invocation.getter(#canChangePowerLevel),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.PushRuleState get pushRuleState =>
      (super.noSuchMethod(
            Invocation.getter(#pushRuleState),
            returnValue: _i3.PushRuleState.notify,
            returnValueForMissingStub: _i3.PushRuleState.notify,
          )
          as _i3.PushRuleState);

  @override
  bool get canChangeJoinRules =>
      (super.noSuchMethod(
            Invocation.getter(#canChangeJoinRules),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.GuestAccess get guestAccess =>
      (super.noSuchMethod(
            Invocation.getter(#guestAccess),
            returnValue: _i3.GuestAccess.canJoin,
            returnValueForMissingStub: _i3.GuestAccess.canJoin,
          )
          as _i3.GuestAccess);

  @override
  bool get canChangeGuestAccess =>
      (super.noSuchMethod(
            Invocation.getter(#canChangeGuestAccess),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get canChangeHistoryVisibility =>
      (super.noSuchMethod(
            Invocation.getter(#canChangeHistoryVisibility),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get encrypted =>
      (super.noSuchMethod(
            Invocation.getter(#encrypted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isExtinct =>
      (super.noSuchMethod(
            Invocation.getter(#isExtinct),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isSpace =>
      (super.noSuchMethod(
            Invocation.getter(#isSpace),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i13.SpaceParent> get spaceParents =>
      (super.noSuchMethod(
            Invocation.getter(#spaceParents),
            returnValue: <_i13.SpaceParent>[],
            returnValueForMissingStub: <_i13.SpaceParent>[],
          )
          as List<_i13.SpaceParent>);

  @override
  List<_i13.SpaceChild> get spaceChildren =>
      (super.noSuchMethod(
            Invocation.getter(#spaceChildren),
            returnValue: <_i13.SpaceChild>[],
            returnValueForMissingStub: <_i13.SpaceChild>[],
          )
          as List<_i13.SpaceChild>);

  @override
  set membership(_i3.Membership? value) => super.noSuchMethod(
    Invocation.setter(#membership, value),
    returnValueForMissingStub: null,
  );

  @override
  set notificationCount(int? value) => super.noSuchMethod(
    Invocation.setter(#notificationCount, value),
    returnValueForMissingStub: null,
  );

  @override
  set highlightCount(int? value) => super.noSuchMethod(
    Invocation.setter(#highlightCount, value),
    returnValueForMissingStub: null,
  );

  @override
  set prev_batch(String? value) => super.noSuchMethod(
    Invocation.setter(#prev_batch, value),
    returnValueForMissingStub: null,
  );

  @override
  set summary(_i3.RoomSummary? value) => super.noSuchMethod(
    Invocation.setter(#summary, value),
    returnValueForMissingStub: null,
  );

  @override
  set states(Map<String, Map<String, _i3.StrippedStateEvent>>? value) =>
      super.noSuchMethod(
        Invocation.setter(#states, value),
        returnValueForMissingStub: null,
      );

  @override
  set ephemerals(Map<String, _i3.BasicEvent>? value) => super.noSuchMethod(
    Invocation.setter(#ephemerals, value),
    returnValueForMissingStub: null,
  );

  @override
  set roomAccountData(Map<String, _i3.BasicEvent>? value) => super.noSuchMethod(
    Invocation.setter(#roomAccountData, value),
    returnValueForMissingStub: null,
  );

  @override
  set partial(bool? value) => super.noSuchMethod(
    Invocation.setter(#partial, value),
    returnValueForMissingStub: null,
  );

  @override
  set lastEvent(_i3.Event? value) => super.noSuchMethod(
    Invocation.setter(#lastEvent, value),
    returnValueForMissingStub: null,
  );

  @override
  set receiptState(_i3.LatestReceiptState? value) => super.noSuchMethod(
    Invocation.setter(#receiptState, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i8.Future<void> postLoad() =>
      (super.noSuchMethod(
            Invocation.method(#postLoad, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i3.StrippedStateEvent? getState(String? typeKey, [String? stateKey = '']) =>
      (super.noSuchMethod(
            Invocation.method(#getState, [typeKey, stateKey]),
            returnValueForMissingStub: null,
          )
          as _i3.StrippedStateEvent?);

  @override
  void setState(_i3.StrippedStateEvent? state) => super.noSuchMethod(
    Invocation.method(#setState, [state]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<List<_i3.User>> loadHeroUsers() =>
      (super.noSuchMethod(
            Invocation.method(#loadHeroUsers, []),
            returnValue: _i8.Future<List<_i3.User>>.value(<_i3.User>[]),
            returnValueForMissingStub: _i8.Future<List<_i3.User>>.value(
              <_i3.User>[],
            ),
          )
          as _i8.Future<List<_i3.User>>);

  @override
  String getLocalizedDisplayname([
    _i3.MatrixLocalizations? i18n = const _i3.MatrixDefaultLocalizations(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalizedDisplayname, [i18n]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#getLocalizedDisplayname, [i18n]),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.method(#getLocalizedDisplayname, [i18n]),
            ),
          )
          as String);

  @override
  _i8.Future<void> setCanonicalAlias(String? canonicalAlias) =>
      (super.noSuchMethod(
            Invocation.method(#setCanonicalAlias, [canonicalAlias]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.Event?> refreshLastEvent({
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshLastEvent, [], {#timeout: timeout}),
            returnValue: _i8.Future<_i3.Event?>.value(),
            returnValueForMissingStub: _i8.Future<_i3.Event?>.value(),
          )
          as _i8.Future<_i3.Event?>);

  @override
  void setEphemeral(_i3.BasicEvent? ephemeral) => super.noSuchMethod(
    Invocation.method(#setEphemeral, [ephemeral]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<String> setName(String? newName) =>
      (super.noSuchMethod(
            Invocation.method(#setName, [newName]),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#setName, [newName]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#setName, [newName]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<String> setDescription(String? newName) =>
      (super.noSuchMethod(
            Invocation.method(#setDescription, [newName]),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#setDescription, [newName]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#setDescription, [newName]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> addTag(String? tag, {double? order}) =>
      (super.noSuchMethod(
            Invocation.method(#addTag, [tag], {#order: order}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#removeTag, [tag]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.SyncUpdate> waitForRoomInSync() =>
      (super.noSuchMethod(
            Invocation.method(#waitForRoomInSync, []),
            returnValue: _i8.Future<_i3.SyncUpdate>.value(
              _FakeSyncUpdate_6(
                this,
                Invocation.method(#waitForRoomInSync, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.SyncUpdate>.value(
              _FakeSyncUpdate_6(
                this,
                Invocation.method(#waitForRoomInSync, []),
              ),
            ),
          )
          as _i8.Future<_i3.SyncUpdate>);

  @override
  _i8.Future<void> markUnread(bool? unread) =>
      (super.noSuchMethod(
            Invocation.method(#markUnread, [unread]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setFavourite(bool? favourite) =>
      (super.noSuchMethod(
            Invocation.method(#setFavourite, [favourite]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setLowPriority(bool? lowPriority) =>
      (super.noSuchMethod(
            Invocation.method(#setLowPriority, [lowPriority]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> setPinnedEvents(List<String>? pinnedEventIds) =>
      (super.noSuchMethod(
            Invocation.method(#setPinnedEvents, [pinnedEventIds]),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#setPinnedEvents, [pinnedEventIds]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#setPinnedEvents, [pinnedEventIds]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  String? getMention(String? mention) =>
      (super.noSuchMethod(
            Invocation.method(#getMention, [mention]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i8.Future<String?> sendTextEvent(
    String? message, {
    String? txid,
    _i3.Event? inReplyTo,
    String? editEventId,
    bool? parseMarkdown = true,
    bool? parseCommands = true,
    String? msgtype = 'm.text',
    String? threadRootEventId,
    String? threadLastEventId,
    StringBuffer? commandStdout,
    bool? addMentions = true,
    bool? displayPendingEvent = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendTextEvent,
              [message],
              {
                #txid: txid,
                #inReplyTo: inReplyTo,
                #editEventId: editEventId,
                #parseMarkdown: parseMarkdown,
                #parseCommands: parseCommands,
                #msgtype: msgtype,
                #threadRootEventId: threadRootEventId,
                #threadLastEventId: threadLastEventId,
                #commandStdout: commandStdout,
                #addMentions: addMentions,
                #displayPendingEvent: displayPendingEvent,
              },
            ),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<String?> sendReaction(
    String? eventId,
    String? key, {
    String? txid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendReaction, [eventId, key], {#txid: txid}),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<String?> sendLocation(
    String? body,
    String? geoUri, {
    String? txid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendLocation, [body, geoUri], {#txid: txid}),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<String?> sendFileEvent(
    _i3.MatrixFile? file, {
    String? txid,
    _i3.Event? inReplyTo,
    String? editEventId,
    int? shrinkImageMaxDimension,
    _i3.MatrixImageFile? thumbnail,
    Map<String, dynamic>? extraContent,
    String? threadRootEventId,
    String? threadLastEventId,
    bool? displayPendingEvent = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendFileEvent,
              [file],
              {
                #txid: txid,
                #inReplyTo: inReplyTo,
                #editEventId: editEventId,
                #shrinkImageMaxDimension: shrinkImageMaxDimension,
                #thumbnail: thumbnail,
                #extraContent: extraContent,
                #threadRootEventId: threadRootEventId,
                #threadLastEventId: threadLastEventId,
                #displayPendingEvent: displayPendingEvent,
              },
            ),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<_i3.EncryptionHealthState> calcEncryptionHealthState() =>
      (super.noSuchMethod(
            Invocation.method(#calcEncryptionHealthState, []),
            returnValue: _i8.Future<_i3.EncryptionHealthState>.value(
              _i3.EncryptionHealthState.allVerified,
            ),
            returnValueForMissingStub:
                _i8.Future<_i3.EncryptionHealthState>.value(
                  _i3.EncryptionHealthState.allVerified,
                ),
          )
          as _i8.Future<_i3.EncryptionHealthState>);

  @override
  _i8.Future<String?> sendEvent(
    Map<String, dynamic>? content, {
    String? type = 'm.room.message',
    String? txid,
    _i3.Event? inReplyTo,
    String? editEventId,
    String? threadRootEventId,
    String? threadLastEventId,
    bool? displayPendingEvent = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendEvent,
              [content],
              {
                #type: type,
                #txid: txid,
                #inReplyTo: inReplyTo,
                #editEventId: editEventId,
                #threadRootEventId: threadRootEventId,
                #threadLastEventId: threadLastEventId,
                #displayPendingEvent: displayPendingEvent,
              },
            ),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> join({bool? leaveIfNotFound = true}) =>
      (super.noSuchMethod(
            Invocation.method(#join, [], {#leaveIfNotFound: leaveIfNotFound}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> leave() =>
      (super.noSuchMethod(
            Invocation.method(#leave, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> forget() =>
      (super.noSuchMethod(
            Invocation.method(#forget, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> kick(String? userID) =>
      (super.noSuchMethod(
            Invocation.method(#kick, [userID]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> ban(String? userID) =>
      (super.noSuchMethod(
            Invocation.method(#ban, [userID]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> unban(String? userID) =>
      (super.noSuchMethod(
            Invocation.method(#unban, [userID]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> setPower(String? userId, int? power) =>
      (super.noSuchMethod(
            Invocation.method(#setPower, [userId, power]),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#setPower, [userId, power]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#setPower, [userId, power]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> invite(String? userID, {String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#invite, [userID], {#reason: reason}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> requestHistory({
    int? historyCount = 30,
    void Function()? onHistoryReceived,
    dynamic direction = _i3.Direction.b,
    _i3.StateFilter? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestHistory, [], {
              #historyCount: historyCount,
              #onHistoryReceived: onHistoryReceived,
              #direction: direction,
              #filter: filter,
            }),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<void> addToDirectChat(String? userID) =>
      (super.noSuchMethod(
            Invocation.method(#addToDirectChat, [userID]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeFromDirectChat() =>
      (super.noSuchMethod(
            Invocation.method(#removeFromDirectChat, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setReadMarker(
    String? eventId, {
    String? mRead,
    bool? public,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setReadMarker,
              [eventId],
              {#mRead: mRead, #public: public},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i14.TimelineChunk?> getEventContext(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getEventContext, [eventId]),
            returnValue: _i8.Future<_i14.TimelineChunk?>.value(),
            returnValueForMissingStub: _i8.Future<_i14.TimelineChunk?>.value(),
          )
          as _i8.Future<_i14.TimelineChunk?>);

  @override
  _i8.Future<void> postReceipt(
    String? eventId, {
    _i3.ReceiptType? type = _i3.ReceiptType.mRead,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postReceipt, [eventId], {#type: type}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.Timeline> getTimeline({
    void Function(int)? onChange,
    void Function(int)? onRemove,
    void Function(int)? onInsert,
    void Function()? onNewEvent,
    void Function()? onUpdate,
    String? eventContextId,
    int? limit = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTimeline, [], {
              #onChange: onChange,
              #onRemove: onRemove,
              #onInsert: onInsert,
              #onNewEvent: onNewEvent,
              #onUpdate: onUpdate,
              #eventContextId: eventContextId,
              #limit: limit,
            }),
            returnValue: _i8.Future<_i3.Timeline>.value(
              _FakeTimeline_7(
                this,
                Invocation.method(#getTimeline, [], {
                  #onChange: onChange,
                  #onRemove: onRemove,
                  #onInsert: onInsert,
                  #onNewEvent: onNewEvent,
                  #onUpdate: onUpdate,
                  #eventContextId: eventContextId,
                  #limit: limit,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.Timeline>.value(
              _FakeTimeline_7(
                this,
                Invocation.method(#getTimeline, [], {
                  #onChange: onChange,
                  #onRemove: onRemove,
                  #onInsert: onInsert,
                  #onNewEvent: onNewEvent,
                  #onUpdate: onUpdate,
                  #eventContextId: eventContextId,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.Timeline>);

  @override
  List<_i3.User> getParticipants([
    List<_i3.Membership>? membershipFilter = const [
      _i3.Membership.join,
      _i3.Membership.invite,
      _i3.Membership.knock,
    ],
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getParticipants, [membershipFilter]),
            returnValue: <_i3.User>[],
            returnValueForMissingStub: <_i3.User>[],
          )
          as List<_i3.User>);

  @override
  _i8.Future<List<_i3.User>> requestParticipants([
    List<_i3.Membership>? membershipFilter = const [
      _i3.Membership.join,
      _i3.Membership.invite,
      _i3.Membership.knock,
    ],
    bool? suppressWarning = false,
    bool? cache,
    bool? enforceFetchFromServer = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#requestParticipants, [
              membershipFilter,
              suppressWarning,
              cache,
              enforceFetchFromServer,
            ]),
            returnValue: _i8.Future<List<_i3.User>>.value(<_i3.User>[]),
            returnValueForMissingStub: _i8.Future<List<_i3.User>>.value(
              <_i3.User>[],
            ),
          )
          as _i8.Future<List<_i3.User>>);

  @override
  _i3.User getUserByMXIDSync(String? mxID) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByMXIDSync, [mxID]),
            returnValue: _FakeUser_8(
              this,
              Invocation.method(#getUserByMXIDSync, [mxID]),
            ),
            returnValueForMissingStub: _FakeUser_8(
              this,
              Invocation.method(#getUserByMXIDSync, [mxID]),
            ),
          )
          as _i3.User);

  @override
  _i3.User unsafeGetUserFromMemoryOrFallback(String? mxID) =>
      (super.noSuchMethod(
            Invocation.method(#unsafeGetUserFromMemoryOrFallback, [mxID]),
            returnValue: _FakeUser_8(
              this,
              Invocation.method(#unsafeGetUserFromMemoryOrFallback, [mxID]),
            ),
            returnValueForMissingStub: _FakeUser_8(
              this,
              Invocation.method(#unsafeGetUserFromMemoryOrFallback, [mxID]),
            ),
          )
          as _i3.User);

  @override
  _i8.Future<_i3.User?> requestUser(
    String? mxID, {
    bool? ignoreErrors = false,
    bool? requestState = true,
    bool? requestProfile = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUser,
              [mxID],
              {
                #ignoreErrors: ignoreErrors,
                #requestState: requestState,
                #requestProfile: requestProfile,
              },
            ),
            returnValue: _i8.Future<_i3.User?>.value(),
            returnValueForMissingStub: _i8.Future<_i3.User?>.value(),
          )
          as _i8.Future<_i3.User?>);

  @override
  _i8.Future<_i3.Event?> getEventById(String? eventID) =>
      (super.noSuchMethod(
            Invocation.method(#getEventById, [eventID]),
            returnValue: _i8.Future<_i3.Event?>.value(),
            returnValueForMissingStub: _i8.Future<_i3.Event?>.value(),
          )
          as _i8.Future<_i3.Event?>);

  @override
  _i3.PowerLevel getPowerLevelByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPowerLevelByUserId, [userId]),
            returnValue: (0 as _i3.PowerLevel),
            returnValueForMissingStub: (0 as _i3.PowerLevel),
          )
          as _i3.PowerLevel);

  @override
  _i8.Future<String> setAvatar(_i3.MatrixFile? file) =>
      (super.noSuchMethod(
            Invocation.method(#setAvatar, [file]),
            returnValue: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#setAvatar, [file]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#setAvatar, [file]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  bool canChangeStateEvent(String? action) =>
      (super.noSuchMethod(
            Invocation.method(#canChangeStateEvent, [action]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.PowerLevel powerForChangingStateEvent(String? action) =>
      (super.noSuchMethod(
            Invocation.method(#powerForChangingStateEvent, [action]),
            returnValue: (0 as _i3.PowerLevel),
            returnValueForMissingStub: (0 as _i3.PowerLevel),
          )
          as _i3.PowerLevel);

  @override
  _i8.Future<void> enableGroupCalls() =>
      (super.noSuchMethod(
            Invocation.method(#enableGroupCalls, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i3.PowerLevel getDefaultPowerLevel(Map<String, dynamic>? powerLevelMap) =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultPowerLevel, [powerLevelMap]),
            returnValue: (0 as _i3.PowerLevel),
            returnValueForMissingStub: (0 as _i3.PowerLevel),
          )
          as _i3.PowerLevel);

  @override
  bool canSendEvent(String? eventType) =>
      (super.noSuchMethod(
            Invocation.method(#canSendEvent, [eventType]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool canSendNotification(
    String? userid, {
    String? notificationType = 'room',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #canSendNotification,
              [userid],
              {#notificationType: notificationType},
            ),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> setPushRuleState(_i3.PushRuleState? newState) =>
      (super.noSuchMethod(
            Invocation.method(#setPushRuleState, [newState]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> redactEvent(
    String? eventId, {
    String? reason,
    String? txid,
    bool? redactAllEdits = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #redactEvent,
              [eventId],
              {#reason: reason, #txid: txid, #redactAllEdits: redactAllEdits},
            ),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> setTyping(bool? isTyping, {int? timeout}) =>
      (super.noSuchMethod(
            Invocation.method(#setTyping, [isTyping], {#timeout: timeout}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setJoinRules(
    _i3.JoinRules? joinRules, {
    List<String>? allowConditionRoomIds,
    String? allowConditionRoomId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setJoinRules,
              [joinRules],
              {
                #allowConditionRoomIds: allowConditionRoomIds,
                #allowConditionRoomId: allowConditionRoomId,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setGuestAccess(_i3.GuestAccess? guestAccess) =>
      (super.noSuchMethod(
            Invocation.method(#setGuestAccess, [guestAccess]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setHistoryVisibility(
    _i3.HistoryVisibility? historyVisibility,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setHistoryVisibility, [historyVisibility]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> enableEncryption({int? algorithmIndex = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#enableEncryption, [], {
              #algorithmIndex: algorithmIndex,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i3.DeviceKeys>> getUserDeviceKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getUserDeviceKeys, []),
            returnValue: _i8.Future<List<_i3.DeviceKeys>>.value(
              <_i3.DeviceKeys>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i3.DeviceKeys>>.value(
              <_i3.DeviceKeys>[],
            ),
          )
          as _i8.Future<List<_i3.DeviceKeys>>);

  @override
  _i8.Future<void> requestSessionKey(String? sessionId, String? senderKey) =>
      (super.noSuchMethod(
            Invocation.method(#requestSessionKey, [sessionId, senderKey]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setSpaceChild(
    String? roomId, {
    List<String>? via,
    String? order,
    bool? suggested,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setSpaceChild,
              [roomId],
              {#via: via, #order: order, #suggested: suggested},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Uri> matrixToInviteLink() =>
      (super.noSuchMethod(
            Invocation.method(#matrixToInviteLink, []),
            returnValue: _i8.Future<Uri>.value(
              _FakeUri_9(this, Invocation.method(#matrixToInviteLink, [])),
            ),
            returnValueForMissingStub: _i8.Future<Uri>.value(
              _FakeUri_9(this, Invocation.method(#matrixToInviteLink, [])),
            ),
          )
          as _i8.Future<Uri>);

  @override
  _i8.Future<void> removeSpaceChild(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#removeSpaceChild, [roomId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<
    ({List<_i3.Event> events, String? nextBatch, DateTime? searchedUntil})
  >
  searchEvents({
    String? searchTerm,
    bool Function(_i3.Event)? searchFunc,
    String? nextBatch,
    int? limit = 1000,
    Set<String>? includeEventTypes = const {
      'm.room.message',
      'm.room.encrypted',
    },
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchEvents, [], {
              #searchTerm: searchTerm,
              #searchFunc: searchFunc,
              #nextBatch: nextBatch,
              #limit: limit,
              #includeEventTypes: includeEventTypes,
            }),
            returnValue:
                _i8.Future<
                  ({
                    List<_i3.Event> events,
                    String? nextBatch,
                    DateTime? searchedUntil,
                  })
                >.value((
                  events: <_i3.Event>[],
                  nextBatch: null,
                  searchedUntil: null,
                )),
            returnValueForMissingStub:
                _i8.Future<
                  ({
                    List<_i3.Event> events,
                    String? nextBatch,
                    DateTime? searchedUntil,
                  })
                >.value((
                  events: <_i3.Event>[],
                  nextBatch: null,
                  searchedUntil: null,
                )),
          )
          as _i8.Future<
            ({
              List<_i3.Event> events,
              String? nextBatch,
              DateTime? searchedUntil,
            })
          >);
}
