// Mocks generated by Mockito from annotations
// in kohera/test/widgets/chat/emoji_suggestion_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i2;
import 'package:kohera/core/models/sticker_pack.dart' as _i7;
import 'package:kohera/core/services/sticker_pack_service.dart' as _i3;
import 'package:kohera/features/chat/services/emoji_autocomplete_controller.dart'
    as _i5;
import 'package:kohera/shared/services/media_resolver.dart' as _i9;
import 'package:matrix/matrix.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTextEditingController_0 extends _i1.SmartFake
    implements _i2.TextEditingController {
  _FakeTextEditingController_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStickerPackService_1 extends _i1.SmartFake
    implements _i3.StickerPackService {
  _FakeStickerPackService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoom_2 extends _i1.SmartFake implements _i4.Room {
  _FakeRoom_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_3 extends _i1.SmartFake implements Duration {
  _FakeDuration_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EmojiAutocompleteController].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmojiAutocompleteController extends _i1.Mock
    implements _i5.EmojiAutocompleteController {
  @override
  _i2.TextEditingController get textController =>
      (super.noSuchMethod(
            Invocation.getter(#textController),
            returnValue: _FakeTextEditingController_0(
              this,
              Invocation.getter(#textController),
            ),
            returnValueForMissingStub: _FakeTextEditingController_0(
              this,
              Invocation.getter(#textController),
            ),
          )
          as _i2.TextEditingController);

  @override
  _i3.StickerPackService get stickerPackService =>
      (super.noSuchMethod(
            Invocation.getter(#stickerPackService),
            returnValue: _FakeStickerPackService_1(
              this,
              Invocation.getter(#stickerPackService),
            ),
            returnValueForMissingStub: _FakeStickerPackService_1(
              this,
              Invocation.getter(#stickerPackService),
            ),
          )
          as _i3.StickerPackService);

  @override
  _i4.Room get room =>
      (super.noSuchMethod(
            Invocation.getter(#room),
            returnValue: _FakeRoom_2(this, Invocation.getter(#room)),
            returnValueForMissingStub: _FakeRoom_2(
              this,
              Invocation.getter(#room),
            ),
          )
          as _i4.Room);

  @override
  Duration get debounceDuration =>
      (super.noSuchMethod(
            Invocation.getter(#debounceDuration),
            returnValue: _FakeDuration_3(
              this,
              Invocation.getter(#debounceDuration),
            ),
            returnValueForMissingStub: _FakeDuration_3(
              this,
              Invocation.getter(#debounceDuration),
            ),
          )
          as Duration);

  @override
  bool get isActive =>
      (super.noSuchMethod(
            Invocation.getter(#isActive),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get query =>
      (super.noSuchMethod(
            Invocation.getter(#query),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#query),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#query),
            ),
          )
          as String);

  @override
  List<_i7.PackImage> get suggestions =>
      (super.noSuchMethod(
            Invocation.getter(#suggestions),
            returnValue: <_i7.PackImage>[],
            returnValueForMissingStub: <_i7.PackImage>[],
          )
          as List<_i7.PackImage>);

  @override
  int get selectedIndex =>
      (super.noSuchMethod(
            Invocation.getter(#selectedIndex),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get hasSuggestions =>
      (super.noSuchMethod(
            Invocation.getter(#hasSuggestions),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void moveUp() => super.noSuchMethod(
    Invocation.method(#moveUp, []),
    returnValueForMissingStub: null,
  );

  @override
  void moveDown() => super.noSuchMethod(
    Invocation.method(#moveDown, []),
    returnValueForMissingStub: null,
  );

  @override
  void confirmSelection() => super.noSuchMethod(
    Invocation.method(#confirmSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  void selectSuggestion(_i7.PackImage? emoji) => super.noSuchMethod(
    Invocation.method(#selectSuggestion, [emoji]),
    returnValueForMissingStub: null,
  );

  @override
  void dismiss() => super.noSuchMethod(
    Invocation.method(#dismiss, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MediaResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaResolver extends _i1.Mock implements _i9.MediaResolver {
  @override
  _i10.Future<_i9.MediaThumbnail?> resolve(
    String? mxcUrl, {
    required double? width,
    required double? height,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #resolve,
              [mxcUrl],
              {#width: width, #height: height},
            ),
            returnValue: _i10.Future<_i9.MediaThumbnail?>.value(),
            returnValueForMissingStub: _i10.Future<_i9.MediaThumbnail?>.value(),
          )
          as _i10.Future<_i9.MediaThumbnail?>);
}
