// Mocks generated by Mockito 5.4.6 from annotations
// in kohera/test/widgets/chat/video_bubble_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;
import 'dart:ui' as _i8;

import 'package:kohera/core/media/media_player.dart' as _i7;
import 'package:kohera/features/chat/services/media_playback_service.dart'
    as _i6;
import 'package:kohera/shared/services/avatar_resolver.dart' as _i9;
import 'package:kohera/shared/services/media_controller.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MediaController].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaController extends _i1.Mock implements _i2.MediaController {
  @override
  bool get isEncrypted =>
      (super.noSuchMethod(
            Invocation.getter(#isEncrypted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get eventId =>
      (super.noSuchMethod(
            Invocation.getter(#eventId),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#eventId),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#eventId),
            ),
          )
          as String);

  @override
  bool get isPendingSend =>
      (super.noSuchMethod(
            Invocation.getter(#isPendingSend),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<_i5.Uint8List> downloadAndDecrypt({bool? getThumbnail = false}) =>
      (super.noSuchMethod(
            Invocation.method(#downloadAndDecrypt, [], {
              #getThumbnail: getThumbnail,
            }),
            returnValue: _i4.Future<_i5.Uint8List>.value(_i5.Uint8List(0)),
            returnValueForMissingStub: _i4.Future<_i5.Uint8List>.value(
              _i5.Uint8List(0),
            ),
          )
          as _i4.Future<_i5.Uint8List>);

  @override
  _i4.Future<String?> getAttachmentUri({
    bool? getThumbnail = false,
    int? width,
    int? height,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAttachmentUri, [], {
              #getThumbnail: getThumbnail,
              #width: width,
              #height: height,
            }),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  Map<String, String>? authHeaders(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#authHeaders, [url]),
            returnValueForMissingStub: null,
          )
          as Map<String, String>?);
}

/// A class which mocks [MediaPlaybackService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaPlaybackService extends _i1.Mock
    implements _i6.MediaPlaybackService {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void registerPlayer(String? eventId, _i7.MediaPlayer? player) =>
      super.noSuchMethod(
        Invocation.method(#registerPlayer, [eventId, player]),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterPlayer(String? eventId) => super.noSuchMethod(
    Invocation.method(#unregisterPlayer, [eventId]),
    returnValueForMissingStub: null,
  );

  @override
  void pauseActive() => super.noSuchMethod(
    Invocation.method(#pauseActive, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AvatarResolver].
///
/// See the documentation for Mockito's code generation for more information.
class MockAvatarResolver extends _i1.Mock implements _i9.AvatarResolver {
  @override
  _i4.Future<_i9.AvatarThumbnail?> resolve(
    String? mxcUrl, {
    required double? size,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resolve, [mxcUrl], {#size: size}),
            returnValue: _i4.Future<_i9.AvatarThumbnail?>.value(),
            returnValueForMissingStub: _i4.Future<_i9.AvatarThumbnail?>.value(),
          )
          as _i4.Future<_i9.AvatarThumbnail?>);
}
