// Mocks generated by Mockito from annotations
// in kohera/test/mocks/matrix_service_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:ui' as _i18;

import 'package:flutter/services.dart' as _i19;
import 'package:flutter/widgets.dart' as _i20;
import 'package:kohera/core/services/account_session.dart' as _i2;
import 'package:kohera/core/services/auth_service.dart' as _i11;
import 'package:kohera/core/services/matrix_service.dart' as _i14;
import 'package:kohera/core/services/sync_service.dart' as _i10;
import 'package:kohera/core/state/key_backup_setup_state.dart' as _i6;
import 'package:kohera/core/state/selection_controller.dart' as _i9;
import 'package:kohera/core/state/uia_interaction_controller.dart' as _i4;
import 'package:kohera/data/repositories/key_backup_repository.dart' as _i7;
import 'package:kohera/data/repositories/space_tree_repository.dart' as _i8;
import 'package:kohera/data/services/avatar_resolver.dart' as _i12;
import 'package:kohera/data/services/matrix_client_service.dart' as _i3;
import 'package:kohera/data/services/media_resolver.dart' as _i13;
import 'package:kohera/data/services/password_cache.dart' as _i5;
import 'package:matrix/matrix.dart' as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAccountSession_0 extends _i1.SmartFake
    implements _i2.AccountSession {
  _FakeAccountSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMatrixClientService_1 extends _i1.SmartFake
    implements _i3.MatrixClientService {
  _FakeMatrixClientService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUiaInteractionController_2 extends _i1.SmartFake
    implements _i4.UiaInteractionController {
  _FakeUiaInteractionController_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePasswordCache_3 extends _i1.SmartFake implements _i5.PasswordCache {
  _FakePasswordCache_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKeyBackupSetupState_4 extends _i1.SmartFake
    implements _i6.KeyBackupSetupState {
  _FakeKeyBackupSetupState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKeyBackupRepository_5 extends _i1.SmartFake
    implements _i7.KeyBackupRepository {
  _FakeKeyBackupRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSpaceTreeRepository_6 extends _i1.SmartFake
    implements _i8.SpaceTreeRepository {
  _FakeSpaceTreeRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectionController_7 extends _i1.SmartFake
    implements _i9.SelectionController {
  _FakeSelectionController_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSyncService_8 extends _i1.SmartFake implements _i10.SyncService {
  _FakeSyncService_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_9 extends _i1.SmartFake implements _i11.AuthService {
  _FakeAuthService_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAvatarResolver_10 extends _i1.SmartFake
    implements _i12.AvatarResolver {
  _FakeAvatarResolver_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMediaResolver_11 extends _i1.SmartFake
    implements _i13.MediaResolver {
  _FakeMediaResolver_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MatrixService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMatrixService extends _i1.Mock implements _i14.MatrixService {
  @override
  String get clientName =>
      (super.noSuchMethod(
            Invocation.getter(#clientName),
            returnValue: _i15.dummyValue<String>(
              this,
              Invocation.getter(#clientName),
            ),
            returnValueForMissingStub: _i15.dummyValue<String>(
              this,
              Invocation.getter(#clientName),
            ),
          )
          as String);

  @override
  bool get disposed =>
      (super.noSuchMethod(
            Invocation.getter(#disposed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.AccountSession get session =>
      (super.noSuchMethod(
            Invocation.getter(#session),
            returnValue: _FakeAccountSession_0(
              this,
              Invocation.getter(#session),
            ),
            returnValueForMissingStub: _FakeAccountSession_0(
              this,
              Invocation.getter(#session),
            ),
          )
          as _i2.AccountSession);

  @override
  _i3.MatrixClientService get matrixClientService =>
      (super.noSuchMethod(
            Invocation.getter(#matrixClientService),
            returnValue: _FakeMatrixClientService_1(
              this,
              Invocation.getter(#matrixClientService),
            ),
            returnValueForMissingStub: _FakeMatrixClientService_1(
              this,
              Invocation.getter(#matrixClientService),
            ),
          )
          as _i3.MatrixClientService);

  @override
  _i4.UiaInteractionController get uia =>
      (super.noSuchMethod(
            Invocation.getter(#uia),
            returnValue: _FakeUiaInteractionController_2(
              this,
              Invocation.getter(#uia),
            ),
            returnValueForMissingStub: _FakeUiaInteractionController_2(
              this,
              Invocation.getter(#uia),
            ),
          )
          as _i4.UiaInteractionController);

  @override
  _i5.PasswordCache get passwordCache =>
      (super.noSuchMethod(
            Invocation.getter(#passwordCache),
            returnValue: _FakePasswordCache_3(
              this,
              Invocation.getter(#passwordCache),
            ),
            returnValueForMissingStub: _FakePasswordCache_3(
              this,
              Invocation.getter(#passwordCache),
            ),
          )
          as _i5.PasswordCache);

  @override
  _i6.KeyBackupSetupState get keyBackupSetupState =>
      (super.noSuchMethod(
            Invocation.getter(#keyBackupSetupState),
            returnValue: _FakeKeyBackupSetupState_4(
              this,
              Invocation.getter(#keyBackupSetupState),
            ),
            returnValueForMissingStub: _FakeKeyBackupSetupState_4(
              this,
              Invocation.getter(#keyBackupSetupState),
            ),
          )
          as _i6.KeyBackupSetupState);

  @override
  _i7.KeyBackupRepository get keyBackupRepository =>
      (super.noSuchMethod(
            Invocation.getter(#keyBackupRepository),
            returnValue: _FakeKeyBackupRepository_5(
              this,
              Invocation.getter(#keyBackupRepository),
            ),
            returnValueForMissingStub: _FakeKeyBackupRepository_5(
              this,
              Invocation.getter(#keyBackupRepository),
            ),
          )
          as _i7.KeyBackupRepository);

  @override
  _i8.SpaceTreeRepository get spaceTree =>
      (super.noSuchMethod(
            Invocation.getter(#spaceTree),
            returnValue: _FakeSpaceTreeRepository_6(
              this,
              Invocation.getter(#spaceTree),
            ),
            returnValueForMissingStub: _FakeSpaceTreeRepository_6(
              this,
              Invocation.getter(#spaceTree),
            ),
          )
          as _i8.SpaceTreeRepository);

  @override
  _i9.SelectionController get selectionController =>
      (super.noSuchMethod(
            Invocation.getter(#selectionController),
            returnValue: _FakeSelectionController_7(
              this,
              Invocation.getter(#selectionController),
            ),
            returnValueForMissingStub: _FakeSelectionController_7(
              this,
              Invocation.getter(#selectionController),
            ),
          )
          as _i9.SelectionController);

  @override
  _i10.SyncService get sync =>
      (super.noSuchMethod(
            Invocation.getter(#sync),
            returnValue: _FakeSyncService_8(this, Invocation.getter(#sync)),
            returnValueForMissingStub: _FakeSyncService_8(
              this,
              Invocation.getter(#sync),
            ),
          )
          as _i10.SyncService);

  @override
  _i11.AuthService get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuthService_9(this, Invocation.getter(#auth)),
            returnValueForMissingStub: _FakeAuthService_9(
              this,
              Invocation.getter(#auth),
            ),
          )
          as _i11.AuthService);

  @override
  _i12.AvatarResolver get avatarResolver =>
      (super.noSuchMethod(
            Invocation.getter(#avatarResolver),
            returnValue: _FakeAvatarResolver_10(
              this,
              Invocation.getter(#avatarResolver),
            ),
            returnValueForMissingStub: _FakeAvatarResolver_10(
              this,
              Invocation.getter(#avatarResolver),
            ),
          )
          as _i12.AvatarResolver);

  @override
  _i13.MediaResolver get mediaResolver =>
      (super.noSuchMethod(
            Invocation.getter(#mediaResolver),
            returnValue: _FakeMediaResolver_11(
              this,
              Invocation.getter(#mediaResolver),
            ),
            returnValueForMissingStub: _FakeMediaResolver_11(
              this,
              Invocation.getter(#mediaResolver),
            ),
          )
          as _i13.MediaResolver);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasSkippedSetup =>
      (super.noSuchMethod(
            Invocation.getter(#hasSkippedSetup),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set isLoggedInForTest(bool? value) => super.noSuchMethod(
    Invocation.setter(#isLoggedInForTest, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void skipSetup() => super.noSuchMethod(
    Invocation.method(#skipSetup, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> activateSessionForTest() =>
      (super.noSuchMethod(
            Invocation.method(#activateSessionForTest, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> init({bool? restoreSession = true}) =>
      (super.noSuchMethod(
            Invocation.method(#init, [], {#restoreSession: restoreSession}),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<bool> login({
    required String? homeserver,
    required String? username,
    required String? password,
    bool? rememberCredentials = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #homeserver: homeserver,
              #username: username,
              #password: password,
              #rememberCredentials: rememberCredentials,
            }),
            returnValue: _i16.Future<bool>.value(false),
            returnValueForMissingStub: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> completeSsoLogin({
    required String? homeserver,
    required String? loginToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeSsoLogin, [], {
              #homeserver: homeserver,
              #loginToken: loginToken,
            }),
            returnValue: _i16.Future<bool>.value(false),
            returnValueForMissingStub: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<void> completeRegistration(
    _i17.RegisterResponse? response, {
    String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #completeRegistration,
              [response],
              {#password: password},
            ),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> handleSoftLogout() =>
      (super.noSuchMethod(
            Invocation.method(#handleSoftLogout, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void didChangeAppLifecycleState(_i18.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(#didChangeAppLifecycleState, [state]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i18.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i18.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<bool> didPopRoute() =>
      (super.noSuchMethod(
            Invocation.method(#didPopRoute, []),
            returnValue: _i16.Future<bool>.value(false),
            returnValueForMissingStub: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  bool handleStartBackGesture(_i19.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
            Invocation.method(#handleStartBackGesture, [backEvent]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void handleUpdateBackGestureProgress(_i19.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(#handleUpdateBackGestureProgress, [backEvent]),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCommitBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
    Invocation.method(#handleCancelBackGesture, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleStatusBarTap() => super.noSuchMethod(
    Invocation.method(#handleStatusBarTap, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<bool> didPushRoute(String? route) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRoute, [route]),
            returnValue: _i16.Future<bool>.value(false),
            returnValueForMissingStub: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> didPushRouteInformation(
    _i20.RouteInformation? routeInformation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#didPushRouteInformation, [routeInformation]),
            returnValue: _i16.Future<bool>.value(false),
            returnValueForMissingStub: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
    Invocation.method(#didChangeMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
    Invocation.method(#didChangeTextScaleFactor, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
    Invocation.method(#didChangePlatformBrightness, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeLocales(List<_i18.Locale>? locales) => super.noSuchMethod(
    Invocation.method(#didChangeLocales, [locales]),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeViewFocus(_i18.ViewFocusEvent? event) => super.noSuchMethod(
    Invocation.method(#didChangeViewFocus, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<_i18.AppExitResponse> didRequestAppExit() =>
      (super.noSuchMethod(
            Invocation.method(#didRequestAppExit, []),
            returnValue: _i16.Future<_i18.AppExitResponse>.value(
              _i18.AppExitResponse.exit,
            ),
            returnValueForMissingStub: _i16.Future<_i18.AppExitResponse>.value(
              _i18.AppExitResponse.exit,
            ),
          )
          as _i16.Future<_i18.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
    Invocation.method(#didHaveMemoryPressure, []),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
    Invocation.method(#didChangeAccessibilityFeatures, []),
    returnValueForMissingStub: null,
  );
}
