import 'package:flutter/material.dart';

class ThemePreset {
  const ThemePreset({
    required this.id,
    required this.name,
    required this.seedColor,
    this.forcedMode,
    this.lightScheme,
    this.darkScheme,
  });

  final String id;
  final String name;
  final Color seedColor;
  final ThemeMode? forcedMode;
  final ColorScheme? lightScheme;
  final ColorScheme? darkScheme;

  ColorScheme light() =>
      lightScheme ?? ColorScheme.fromSeed(seedColor: seedColor);

  ColorScheme dark() =>
      darkScheme ??
      ColorScheme.fromSeed(seedColor: seedColor, brightness: Brightness.dark);
}

const _presets = <ThemePreset>[
  // ── Core themes ──────────────────────────────────────────────
  ThemePreset(
    id: 'black',
    name: 'Black',
    seedColor: Color(0xFF000000),
    forcedMode: ThemeMode.dark,
    lightScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF424242),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFE0E0E0),
      onPrimaryContainer: Color(0xFF212121),
      secondary: Color(0xFF616161),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFEEEEEE),
      onSecondaryContainer: Color(0xFF424242),
      tertiary: Color(0xFF757575),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFF5F5F5),
      onTertiaryContainer: Color(0xFF424242),
      error: Color(0xFFB3261E),
      onError: Color(0xFFFFFFFF),
      surface: Color(0xFFFAFAFA),
      onSurface: Color(0xFF1B1B1B),
      onSurfaceVariant: Color(0xFF616161),
      outline: Color(0xFF9E9E9E),
      outlineVariant: Color(0xFFE0E0E0),
      surfaceContainerLowest: Color(0xFFFFFFFF),
      surfaceContainerLow: Color(0xFFF5F5F5),
      surfaceContainer: Color(0xFFF0F0F0),
      surfaceContainerHigh: Color(0xFFEBEBEB),
      surfaceContainerHighest: Color(0xFFE0E0E0),
    ),
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFBDBDBD),
      onPrimary: Color(0xFF000000),
      primaryContainer: Color(0xFF424242),
      onPrimaryContainer: Color(0xFFE0E0E0),
      secondary: Color(0xFF9E9E9E),
      onSecondary: Color(0xFF000000),
      secondaryContainer: Color(0xFF333333),
      onSecondaryContainer: Color(0xFFBDBDBD),
      tertiary: Color(0xFF757575),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFF2C2C2C),
      onTertiaryContainer: Color(0xFF9E9E9E),
      error: Color(0xFFF2B8B5),
      onError: Color(0xFF601410),
      surface: Color(0xFF121212),
      onSurface: Color(0xFFE0E0E0),
      onSurfaceVariant: Color(0xFF9E9E9E),
      outline: Color(0xFF616161),
      outlineVariant: Color(0xFF333333),
      surfaceContainerLowest: Color(0xFF0A0A0A),
      surfaceContainerLow: Color(0xFF1A1A1A),
      surfaceContainer: Color(0xFF1E1E1E),
      surfaceContainerHigh: Color(0xFF252525),
      surfaceContainerHighest: Color(0xFF2C2C2C),
    ),
  ),
  ThemePreset(
    id: 'white',
    name: 'White',
    seedColor: Color(0xFFBDBDBD),
    forcedMode: ThemeMode.light,
    lightScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF5C6670),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFDDE3EA),
      onPrimaryContainer: Color(0xFF3A4249),
      secondary: Color(0xFF6B7680),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFE8ECF0),
      onSecondaryContainer: Color(0xFF4A535B),
      tertiary: Color(0xFF7D8690),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFF0F2F5),
      onTertiaryContainer: Color(0xFF5C6670),
      error: Color(0xFFB3261E),
      onError: Color(0xFFFFFFFF),
      surface: Color(0xFFFFFFFF),
      onSurface: Color(0xFF1A1C1E),
      onSurfaceVariant: Color(0xFF6B7680),
      outline: Color(0xFFAEB5BD),
      outlineVariant: Color(0xFFDDE3EA),
      surfaceContainerLowest: Color(0xFFFFFFFF),
      surfaceContainerLow: Color(0xFFF8F9FA),
      surfaceContainer: Color(0xFFF2F4F5),
      surfaceContainerHigh: Color(0xFFECEEF0),
      surfaceContainerHighest: Color(0xFFE8EAEC),
    ),
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFBEC6D0),
      onPrimary: Color(0xFF2A3139),
      primaryContainer: Color(0xFF404850),
      onPrimaryContainer: Color(0xFFDDE3EA),
      secondary: Color(0xFFADB7C1),
      onSecondary: Color(0xFF333B43),
      secondaryContainer: Color(0xFF4A535B),
      onSecondaryContainer: Color(0xFFCDD5DD),
      tertiary: Color(0xFF9DA7B1),
      onTertiary: Color(0xFF3E464E),
      tertiaryContainer: Color(0xFF545C64),
      onTertiaryContainer: Color(0xFFBEC6D0),
      error: Color(0xFFF2B8B5),
      onError: Color(0xFF601410),
      surface: Color(0xFF1A1C1E),
      onSurface: Color(0xFFE2E4E6),
      onSurfaceVariant: Color(0xFF9DA7B1),
      outline: Color(0xFF6B7680),
      outlineVariant: Color(0xFF333B43),
      surfaceContainerLowest: Color(0xFF111315),
      surfaceContainerLow: Color(0xFF1E2023),
      surfaceContainer: Color(0xFF232628),
      surfaceContainerHigh: Color(0xFF2A2D30),
      surfaceContainerHighest: Color(0xFF333538),
    ),
  ),
  ThemePreset(
    id: 'dark',
    name: 'Dark',
    seedColor: Color(0xFF546E7A),
    forcedMode: ThemeMode.dark,
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF90A4AE),
      onPrimary: Color(0xFF1A2327),
      primaryContainer: Color(0xFF37474F),
      onPrimaryContainer: Color(0xFFB0BEC5),
      secondary: Color(0xFF80CBC4),
      onSecondary: Color(0xFF1A2327),
      secondaryContainer: Color(0xFF2C4A47),
      onSecondaryContainer: Color(0xFFA8DDD8),
      tertiary: Color(0xFFA5D6A7),
      onTertiary: Color(0xFF1A2327),
      tertiaryContainer: Color(0xFF2E4A30),
      onTertiaryContainer: Color(0xFFC8E6C9),
      error: Color(0xFFEF9A9A),
      onError: Color(0xFF3B1010),
      surface: Color(0xFF1C2529),
      onSurface: Color(0xFFE0E4E7),
      onSurfaceVariant: Color(0xFF8E9EA6),
      outline: Color(0xFF5C6E76),
      outlineVariant: Color(0xFF344046),
      surfaceContainerLowest: Color(0xFF141B1E),
      surfaceContainerLow: Color(0xFF1C2529),
      surfaceContainer: Color(0xFF212C31),
      surfaceContainerHigh: Color(0xFF283438),
      surfaceContainerHighest: Color(0xFF303D42),
    ),
  ),

  // ── Color themes ─────────────────────────────────────────────
  ThemePreset(
    id: 'ocean',
    name: 'Ocean',
    seedColor: Color(0xFF006D77),
  ),
  ThemePreset(
    id: 'purple',
    name: 'Purple',
    seedColor: Color(0xFF6750A4),
  ),
  ThemePreset(
    id: 'forest',
    name: 'Forest',
    seedColor: Color(0xFF2E7D32),
  ),

  // ── Catppuccin-inspired themes ───────────────────────────────
  ThemePreset(
    id: 'mocha',
    name: 'Mocha',
    seedColor: Color(0xFFCBA6F7),
    forcedMode: ThemeMode.dark,
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFCBA6F7),
      onPrimary: Color(0xFF1E1E2E),
      primaryContainer: Color(0xFF45275A),
      onPrimaryContainer: Color(0xFFE8D5FF),
      secondary: Color(0xFFF5C2E7),
      onSecondary: Color(0xFF1E1E2E),
      secondaryContainer: Color(0xFF5A3050),
      onSecondaryContainer: Color(0xFFF5D5EE),
      tertiary: Color(0xFFF38BA8),
      onTertiary: Color(0xFF1E1E2E),
      tertiaryContainer: Color(0xFF5A2535),
      onTertiaryContainer: Color(0xFFF5C5D0),
      error: Color(0xFFF38BA8),
      onError: Color(0xFF1E1E2E),
      surface: Color(0xFF1E1E2E),
      onSurface: Color(0xFFCDD6F4),
      onSurfaceVariant: Color(0xFFA6ADC8),
      outline: Color(0xFF6C7086),
      outlineVariant: Color(0xFF45475A),
      surfaceContainerLowest: Color(0xFF11111B),
      surfaceContainerLow: Color(0xFF181825),
      surfaceContainer: Color(0xFF1E1E2E),
      surfaceContainerHigh: Color(0xFF262637),
      surfaceContainerHighest: Color(0xFF313244),
    ),
  ),
  ThemePreset(
    id: 'macchiato',
    name: 'Macchiato',
    seedColor: Color(0xFFC6A0F6),
    forcedMode: ThemeMode.dark,
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFC6A0F6),
      onPrimary: Color(0xFF24273A),
      primaryContainer: Color(0xFF42255A),
      onPrimaryContainer: Color(0xFFE4D0FF),
      secondary: Color(0xFFF0C6C6),
      onSecondary: Color(0xFF24273A),
      secondaryContainer: Color(0xFF5A3040),
      onSecondaryContainer: Color(0xFFF5D8D8),
      tertiary: Color(0xFFED8796),
      onTertiary: Color(0xFF24273A),
      tertiaryContainer: Color(0xFF582530),
      onTertiaryContainer: Color(0xFFF5C0C8),
      error: Color(0xFFED8796),
      onError: Color(0xFF24273A),
      surface: Color(0xFF24273A),
      onSurface: Color(0xFFCAD3F5),
      onSurfaceVariant: Color(0xFFA5ADCB),
      outline: Color(0xFF6E738D),
      outlineVariant: Color(0xFF494D64),
      surfaceContainerLowest: Color(0xFF181926),
      surfaceContainerLow: Color(0xFF1E2030),
      surfaceContainer: Color(0xFF24273A),
      surfaceContainerHigh: Color(0xFF2C2F44),
      surfaceContainerHighest: Color(0xFF363A4F),
    ),
  ),
  ThemePreset(
    id: 'frappe',
    name: 'Frappé',
    seedColor: Color(0xFFBBBBF6),
    forcedMode: ThemeMode.dark,
    darkScheme: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFBBBBF6),
      onPrimary: Color(0xFF303446),
      primaryContainer: Color(0xFF3E3F6E),
      onPrimaryContainer: Color(0xFFD8D8FF),
      secondary: Color(0xFFF2D5CF),
      onSecondary: Color(0xFF303446),
      secondaryContainer: Color(0xFF5A4040),
      onSecondaryContainer: Color(0xFFF5E0DA),
      tertiary: Color(0xFFE78284),
      onTertiary: Color(0xFF303446),
      tertiaryContainer: Color(0xFF552528),
      onTertiaryContainer: Color(0xFFF5B8BA),
      error: Color(0xFFE78284),
      onError: Color(0xFF303446),
      surface: Color(0xFF303446),
      onSurface: Color(0xFFC6D0F5),
      onSurfaceVariant: Color(0xFFA5ADCE),
      outline: Color(0xFF737994),
      outlineVariant: Color(0xFF51576D),
      surfaceContainerLowest: Color(0xFF232634),
      surfaceContainerLow: Color(0xFF292C3C),
      surfaceContainer: Color(0xFF303446),
      surfaceContainerHigh: Color(0xFF383C50),
      surfaceContainerHighest: Color(0xFF414559),
    ),
  ),
  ThemePreset(
    id: 'latte',
    name: 'Latte',
    seedColor: Color(0xFF8839EF),
    forcedMode: ThemeMode.light,
    lightScheme: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF8839EF),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFECDDFF),
      onPrimaryContainer: Color(0xFF5C2D91),
      secondary: Color(0xFF179299),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFB5ECEF),
      onSecondaryContainer: Color(0xFF0E6166),
      tertiary: Color(0xFFDF8E1D),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFE0A0),
      onTertiaryContainer: Color(0xFF7A4E10),
      error: Color(0xFFD20F39),
      onError: Color(0xFFFFFFFF),
      surface: Color(0xFFEFF1F5),
      onSurface: Color(0xFF4C4F69),
      onSurfaceVariant: Color(0xFF6C6F85),
      outline: Color(0xFF9CA0B0),
      outlineVariant: Color(0xFFCCD0DA),
      surfaceContainerLowest: Color(0xFFFFFFFF),
      surfaceContainerLow: Color(0xFFE6E9EF),
      surfaceContainer: Color(0xFFDCE0E8),
      surfaceContainerHigh: Color(0xFFD4D7E0),
      surfaceContainerHighest: Color(0xFFCCD0DA),
    ),
  ),
];

final themePresets = Map<String, ThemePreset>.fromEntries(
  _presets.map((p) => MapEntry(p.id, p)),
);

List<ThemePreset> get themePresetList => _presets;

ThemePreset? getPreset(String? id) => id != null ? themePresets[id] : null;
